title: hostingvertailu.info
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-money
exclude:
  - vendor
  - CNAME
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
lang: fi
